### ISSUE TITLE
Drop OracleJDK support?

### ISSUE THREAD

**Issue by apolloclark** [idealista/java_role#102]
### Prerequisites

* [X ] Put an X between the brackets on this line if you have done all of the following:
    * Checked that your issue isn't already filled: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aidealista
    * Checked that there is not already provided the described functionality

### Description

Should support for OracleJDK be dropped? I've been trying to debug the new updated OracleJDK urls, it requires registering a developer account, and using a limited time auth token in the URL to download. In theory I could add an Ansible step to login with my Oracle developer credentials, and grep the auth token from the HTTP response...

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by jnogol** [comment]
Hi @apolloclark,

Yep, Oracle is not making things easy. Anyways, we specify in [our README](https://github.com/idealista/java_role#oraclejdk) that we're dropping OracleJDK support in future releases.

Regards,
Jose

**Comment by dortegau** [comment]
OracleJDK support is dropped in the new release
