### ISSUE TITLE
Update installation for Debian 10 (buster)

### ISSUE THREAD

**Issue by sorobon** [idealista/java_role#107]
### Prerequisites

* [ ] Put an X between the brackets on this line if you have done all of the following:
    * Checked that your issue isn't already filled: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aidealista
    * Checked that there is not already provided the described functionality

### Description

Installation fails in debian 10 systems.

### Versions

All

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by apolloclark** [comment]
This is fixed, in my pull request https://github.com/idealista/java_role/pull/103

**Comment by frantsao** [comment]
Fixed in 5.1.0 release.
