### ISSUE TITLE
Add CentOS 8 support

### ISSUE THREAD

**Issue by apolloclark** [idealista/java_role#114]
### Prerequisites

* [X ] Put an X between the brackets on this line if you have done all of the following:
    * Checked that your issue isn't already filled: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aidealista
    * Checked that there is not already provided the described functionality

### Description

Add CentOS 8 support

### Additional Information

I'll open a new PR for this over the weekend.

**Comment by dortegau** [comment]
CentOS is now supported using v5.1.0
