### ISSUE TITLE
Add Support for 11.5.x

### ISSUE THREAD

**Issue by apolloclark** [idealista/java_role#115]
### Prerequisites

* [X ] Put an X between the brackets on this line if you have done all of the following:
    * Checked that your issue isn't already filled: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aidealista
    * Checked that there is not already provided the described functionality

### Description

Add Support for 11.5.x

**Comment by frantsao** [comment]
I'm closing this issue, I understand you mean support for 11.0.5, and it has been added.
