### ISSUE TITLE
[FEATURE] add support for java zulu implementation

### ISSUE THREAD

**Issue by TomaszMru** [idealista/java_role#147]
### Description

add implementation azul to choose 
https://www.azul.com/downloads/zulu-community/?package=jdk

### Why is this needed?

Many of software indicate this implementation as recommended distribution for instance talend open studio
https://help.talend.com/r/3tqeAEtb4sPbcKls967Srg/kzqC6NETFw7ouOx1jA4nLA

### Additional Information

[Any additional information, configuration or data.]

**Comment by vicsufer** [comment]
Hi Thomas, We're not actively looking forward to implement support for that JDK ourselves, however of course pull requests are open.

We do provide a way to implement non-supported JDK by overriding certain variables, for instance:
https://github.com/idealista/java_role/blob/d484a9b609b3dca0834f8ba1b9e8e40ddbd1bb3d/vars/adoptopenjdk/Debian-10.yml#L2-L16

In your playbook group_vars declare the above variables (without the starting underscore) and place the corresponding values for the zulu implementation.
