### ISSUE TITLE
Add Amazon Corretto support

### ISSUE THREAD

**Issue by dortegau** [idealista/java_role#39]
### Description

Should this role support [Amazon Corretto](https://aws.amazon.com/es/corretto/)?

Note: AFAIK only supports Amazon Linux, MacOS, Windows and Docker (but with additional support planned for General Availability)

### Additional Information

- https://docs.aws.amazon.com/corretto/#lang/es_es

**Comment by frantsao** [comment]
And/or [AdoptOpenJDK](https://adoptopenjdk.net/)...
