### ISSUE TITLE
DockerHub image with systemd

### ISSUE THREAD

**Issue by jnogol** [idealista/java_role#77]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Checked that your issue isn't already filled: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aidealista
    * Checked that there is not already provided the described functionality

### Description

In the new [Docker Hub image](https://hub.docker.com/r/idealista/jdk), systemd is not available. Make another image with it.

**Comment by dortegau** [comment]
IMHO systemd should be installed in the image that requires systemd and java.
